{{- if .Values.SriovNetwork.enable }}
{{- $initialContext := . }}
{{- $SriovNetwork := .Values.SriovNetwork.SriovNetworks }}
{{- range $SriovNetwork }}
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: {{ $initialContext.Release.Name }}-{{ .name }}-sriov-network
  namespace: {{ .namespace }}
spec:
  resourceName: {{ .resourceName }}
  networkNamespace: {{ $initialContext.Release.Namespace }}
---
{{- end }}
{{- end }}