{{- if .Values.SriovNetworkNodePolicy.enable }}
{{- $initialContext := . }}
{{- $SriovNetworkNodePolicy := .Values.SriovNetworkNodePolicy.SriovNetworkNodePolicys }}
{{- range $SriovNetworkNodePolicy }}
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: {{ $initialContext.Release.Name }}-{{ .name }}-snnp
  namespace: {{ .namespace }} 
spec:
  resourceName: {{ .resourceName }} 
  nodeSelector:
    {{ .nodeSelector.key }}: {{ .nodeSelector.value | quote }}
  numVfs: {{ .numVfs }}
  {{- include "SriovNetworkNodePolicy.spec.nicSelector" . | indent 2}}
---
{{- end }}
{{- end }}