# COMPUTE

 ## @param vm
 ##
vm:

  ## @param vm.enable
  ##
  enable: ""

  ## @param vm.name
  ##
  name: ""

  ## @param vm.running
  ##
  running: ""

  ## @param vm.nodeSelector
  ## E.g. 
  ## key: key
  ## value: value
  ##
  nodeSelector: {}

  ## @param vm.template
  ##
  template:

    ## @param vm.template.metadata
    ##
    metadata:

      ## @param vm.template.labels
      ## E.g. 
      ## - key: kubevirt.io/vm
      ##   value: value
      ##
      labels: []

      ## @param vm.template.annotations
      ## E.g. 
      ## - key: cpu-load-balancing.crio.io
      ##   value: disable
      ##
      annotations: []

    ## @param vm.template.spec
    ##
    spec:

      ## @param vm.template.spec.domain
      ##
      domain:

        ## @param vm.template.spec.domain.resources
        ## E.g.
        ## requests:
        ##   memory: 1024M
        ##
        resources: {}

        ## @param vm.template.spec.domain.memory
        ## E.g.
        ## guest: 4Gi
        ## hugepages:
        ##   pageSize: 1Gi
        ##
        memory: {}

        ## @param vm.template.spec.domain.devices
        ## E.g.
        ## disks:
        ## - name: containerdisk
        ##   disk:
        ##     bus: virtio
        ## - name: cloudinitdisk
        ##   disk:
        ##     bus: virtio
        ## interfaces:
        ## - masquerade: {}
        ##   name: default
        ## networkInterfaceMultiqueue: "false"
        ## autoattachGraphicsDevice: "false"
        ## autoattachMemBalloon: "true"
        ## autoattachSerialConsole: "true"
        ##
        devices: {}

        ## @param vm.template.spec.domain.cpu
        ## E.g.
        ## cores: 2
        ## sockets: 2
        ## threads: 2
        ## dedicatedCpuPlacement: "true"
        ## isolateEmulatorThread: "true"
        ## model: passthrough
        ## numa:
        ##   key: guestMappingPassthrough
        ## realtime: "true"
        ##
        cpu: {}
          
        ## @param vm.template.spec.domain.ioThreadsPolicy
        ##
        ioThreadsPolicy: ""

      ## @param vm.template.spec.volumes
      ## E.g.
      ## - image: registry.redhat.io/rhel8/rhel-guest-image:latest
      ##   name: containerdisk
      ##   type: containerDisk
      ## - dataVolume:
      ##     name: rt-dv-dv
      ##   name: root-disk
      ##   type: dataVolume
      ## - cloudInitNoCloud:
      ##     networkData:  
      ##       ethernets:
      ##         eth0:
      ##           addresses:
      ##           - fd10:0:2::2/120
      ##           dhcp4: true
      ##           gateway6: fd10:0:2::1
      ##         eth1:
      ##           addresses:
      ##           - 10.200.0.2/24
      ##           dhcp4: true
      ##           gateway6: fd10:0:2::1
      ##       version: 2
      ##
      volumes: []

      ## @param vm.template.spec.tolerations
      ## E.g.
      ## - key: node-role.kubernetes.io/worker-realtime
      ##   operator: Exists
      ##
      tolerations: []

      ## @param vm.template.spec.terminationGracePeriodSeconds
      ##
      terminationGracePeriodSeconds: ""
  
  ## @param vm.networks 
  ## E.g. 
  ## - name: default
  ##   type: pod
  ## - name: bridge-net
  ##   type: bridge
  ##   networkName: bridge-nad
  ## - name: sriov-net-1 
  ##   type: multus
  ##   networkName: sriov-network-1-sriov-network
  ##
  networks: []

  ## @param vm.dataVolumeTemplates
  ## E.g.
  ## - apiVersion: cdi.kubevirt.io/v1beta1
  ##   kind: DataVolume
  ##   metadata:
  ##     name: rhel9-realtime
  ##   spec:
  ##     sourceRef:
  ##       kind: DataSource
  ##       name: rhel9
  ##       namespace: openshift-virtualization-os-images
  ##     storage:
  ##       resources:
  ##         requests:
  ##           storage: 30Gi
  ##
  dataVolumeTemplates: []

mcp:
  enable: false
  labels:
  - key: machineconfiguration.openshift.io/role
    value: worker-realtime
  machineConfigSelector:
    matchExpressions:
      matchExpressions:
      - key: machineconfiguration.openshift.io/role
        operator: In
        values:
        - worker
        - worker-realtime
  nodeSelector:
    matchLabels:
      key: node-role.kubernetes.io/worker-realtime
      value: ''

PerformanceProfile:
  enable: false
  cpu:
    isolated: 4-39,44-79
    reserved: 0-3,40-43
  globallyDisableIrqLoadBalancing: true
  hugepages:
    defaultHugepagesSize: 1G
    pages:
    - count: 8
      size: 1G
  nodeSelector:
    key: node-role.kubernetes.io/worker-realtime
    value: ''
  numa:
    topologyPolicy: single-numa-node
  realTimeKernel:
    enabled: true
  workloadHints:
    highPowerConsumption: true
    realTime: true

# NETWORK
nncp:
  enable: false
  nncps:
  - name: 1
    interfaces:
    - name: br1
      type: linux-bridge
      state: up
      ports:
      - eno3
    nodeSelector:
      key: node-role.kubernetes.io/worker
      value: ""

nad:
  enable: false
  name: bridge-nad
  network:
    bridge: br1
    cniVersion: 0.3.1
    ipam: '{}'
    macspoofchk: true
    name: bridge-network
    preserveDefaultVlan: false
    type: cnv-bridge
    vlan: 861

SriovNetwork:
  enable: false
  SriovNetworks:
  - name: 1
    namespace: openshift-sriov-network-operator
    resourceName: sriov_net

SriovNetworkNodePolicy:
  enable: false
  SriovNetworkNodePolicys:
  - name: 1
    namespace: openshift-sriov-network-operator
    nicSelector:
      pfNames:
      - eno2
      - eno2
      - eno2
    nodeSelector:
      key: feature.node.kubernetes.io/network-sriov.capable
      value: true
    numVfs: 32
    resourceName: sriov_net

# STORAGE
dv:
  enable: false
  pvc:
    accessModes:
    - ReadWriteOnce
    enable: false
    resources:
      requests:
        storage: 1Gi
    storageClassName: ocs-storagecluster-ceph-rbd
    volumeMode: Block

  ## @param dv.source
  ## E.g.
  ## registry:
  ##   pullMethod: node
  ##   secretRef: pull-secret
  ##   url: registry.redhat.io/rhel8/rhel-guest-image:latest
  source:

    ## @param dv.source.blank
    blank: ""

    ## @param dv.source.registry
    ## E.g.
    ## registry:
    ##   pullMethod: node
    ##   secretRef: pull-secret
    ##   url: registry.redhat.io/rhel8/rhel-guest-image:latest  
    registry: {}

    ## @param dv.source.pvc
    ## E.g.
    ## name: rhel9-dede71e24368
    ## namespace: openshift-virtualization-os-images  
    pvc: {}

  ## @param dv.sourceRef 
  ## E.g.
  ## kind: DataVolume:
  ## name: rhel8-15728c1d93e3
  ## namespace: openshift-virtualization-os-images 
  sourceRef: {}

  ## @param dv.storage
  ## E.g.
  ## accessModes:
  ##   - ReadWriteOnce
  ##   resources:
  ##     requests:
  ##       storage: 1Gi
  ##   storageClassName: ocs-storagecluster-ceph-rbd  
  storage: {}

pvc:
  enable: false
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-ceph-rbd