# COMPUTE
vm:
  enable: false
  vms:
  - name: 1
    running: true
    domain:
      cpu:
        cores:
          value: 2
        dedicatedCpuPlacement:
          value: true
        isolateEmulatorThread:
          value: true
        model:
          value: passthrough
        numa:
          key: guestMappingPassthrough
        realtime: "true"
        sockets:
          value: 2
        threads:
          value: 2
      devices:
        autoattachGraphicsDevice:
          value: false
        autoattachMemBalloon:
          value: false
        autoattachSerialConsole:
          value: true
        disks:
        - bus: virtio
          name: cloudinitdisk
        - bus: virtio
          name: containerdisk
        interfaces:
          - name: default
            type: masquerade
        networkInterfaceMultiqueue:
          value: true
      ioThreadsPolicy:
        value: auto
      memory:
        enable: false
        guest: 4Gi
        hugepages:
          enable: false
          pageSize: 1Gi
      resources:
        requests:
          memory: 1024M
      terminationGracePeriodSeconds:
        value: 0
    networks:
      - name: default
        type: pod
    nodeSelector:
      key: key
      value: value
    template:
      metadata:
        annotations:
          - key: cpu-load-balancing.crio.io
            value: disable
          - key: cpu-quota.crio.io
            value: disable
          - key: irq-load-balancing.crio.io
            value: disable
      spec:
        tolerations:
          enable: false
          tolerations:
          - key: node-role.kubernetes.io/worker-realtime
            operator: Exists
    volumes:
    - image: registry.redhat.io/rhel8/rhel-guest-image:latest
      name: containerdisk
      type: containerDisk
    - dataVolume:
        name: rt-dv-dv
      name: root-disk
      type: dataVolume
    - cloudInitNoCloud:
        networkData:
          ethernets:
            - addresses:
                - fd10:0:2::2/120
              dhcp4:
                value: true
              gateway6:
                value: fd10:0:2::1
              name: eth0
            - addresses:
                - 10.200.0.2/24
              dhcp4:
                value: true
              gateway6:
                value: true
              name: eth1
          version: 2
        userData:
          password: p
          user: u
      name: cloudinitdisk
      type: cloudInitNoCloud

mcp:
  enable: false
  labels:
  - key: machineconfiguration.openshift.io/role
    value: worker-realtime
  machineConfigSelector:
    matchExpressions:
      enable: false
      matchExpressions:
      - key: machineconfiguration.openshift.io/role
        operator: In
        values:
        - worker
        - worker-realtime
  nodeSelector:
    matchLabels:
      enable: false
      key: node-role.kubernetes.io/worker-realtime
      value: ''

PerformanceProfile:
cpu:
  isolated: 4-39,44-79
  reserved: 0-3,40-43
enable: false
globallyDisableIrqLoadBalancing: true
hugepages:
  defaultHugepagesSize: 1G
  pages:
  - count: 8
    size: 1G
nodeSelector:
  key: node-role.kubernetes.io/worker-realtime
  value: ''
numa:
  topologyPolicy: single-numa-node
realTimeKernel:
  enabled: true
workloadHints:
  highPowerConsumption: true
  realTime: true

# NETWORK
nncp:
  enable: false
  nncps:
  - interfaces:
    - name: br1
      ports:
      - ens1f3
      state: up
      type: linux-bridge
    name: 1
    nodeSelector:
      enable: false
      key: kubernetes.io/hostname
      value: master2.bm02-ibm.ibmc.cnv-qe.rhood.us
  - interfaces:
    - name: br1
      ports:
      - ens1f3
      state: up
      type: linux-bridge
    name: 2
    nodeSelector:
      enable: false
      key: mykey
      value: myval

nad:
  enable: false
  name: bridge-nad
  network:
    bridge: br1
    cniVersion: 0.3.1
    ipam:
      enable: false
      value: '{}'
    macspoofchk: true
    name: bridge-network
    preserveDefaultVlan:
      enable: false
      value: false
    type: cnv-bridge
    vlan:
      enable: false
      value: 861

SriovNetwork:
  SriovNetworks:
  - name: 1
    namespace: openshift-sriov-network-operator
    resourceName: sriov_net
  enable: false

SriovNetworkNodePolicy:
  SriovNetworkNodePolicys:
  - name: 1
    namespace: openshift-sriov-network-operator
    nicSelector:
      pfNames:
      - eno2
      - eno2
      - eno2
    nodeSelector:
      key: feature.node.kubernetes.io/network-sriov.capable
      value: true
    numVfs: 32
    resourceName: sriov_net
  enable: false

# STORAGE
dv:
  enable: false
  pvc:
    accessModes:
    - ReadWriteOnce
    enable: false
    resources:
      requests:
        storage: 1Gi
    storageClassName: ocs-storagecluster-ceph-rbd
    volumeMode: Block
  source:
    blank:
      enable: false
    registry:
      enable: false
      pullMethod:
        enable: false
        value: node
      secretRef:
        enable: false
        value: pull-secret
      url: registry.redhat.io/rhel8/rhel-guest-image:latest

pvc:
  accessModes:
  - ReadWriteOnce
  enable: false
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-ceph-rbd