# COMPUTE
vm:
  enable: false
  vms:
  - name: 1
    running: true
    networks:
      - name: default
        type: pod
    nodeSelector:
      key: key
      value: value
    template:
      metadata:
        labels:
          - key: kubevirt.io/vm
            value: value
        annotations:
          - key: cpu-load-balancing.crio.io
            value: disable
          - key: cpu-quota.crio.io
            value: disable
          - key: irq-load-balancing.crio.io
            value: disable
      spec:
        domain:
          cpu:
            dedicatedCpuPlacement: "true"
            isolateEmulatorThread: "true"
            model: passthrough
            numa:
              key: guestMappingPassthrough
            realtime: "true"
            cores: 2
            sockets: 2
            threads: 2
          devices:
            autoattachGraphicsDevice: "true"
            autoattachMemBalloon: "false"
            autoattachSerialConsole: "true"
            disks:
            - bus: virtio
              name: cloudinitdisk
            - bus: virtio
              name: containerdisk
            interfaces:
              - name: default
                type: masquerade
            networkInterfaceMultiqueue: "true"
          ioThreadsPolicy: auto
          memory:
            guest: 4Gi
            hugepages:
              pageSize: 1Gi
          resources:
            requests:
              memory: 1024M
        tolerations:
          - key: node-role.kubernetes.io/worker-realtime
            operator: Exists
        terminationGracePeriodSeconds: "0"
    
    ## @param vm.vms.volumes List of volumes that can be mounted by disks belonging to the vmi
    ## E.g.
    ## - image: registry.redhat.io/rhel8/rhel-guest-image:latest
    ##   name: containerdisk
    ##   type: containerDisk
    ## - dataVolume:
    ##     name: rt-dv-dv
    ##   name: root-disk
    ##   type: dataVolume
    ## - cloudInitNoCloud:
    ##     networkData:
    ##       ethernets:
    ##         - addresses:
    ##             - fd10:0:2::2/120
    ##           dhcp4: "true"
    ##           gateway6: fd10:0:2::1
    ##           name: eth0
    ##         - addresses:
    ##             - 10.200.0.2/24
    ##           dhcp4: "true"
    ##           gateway6: fd10:0:2::1
    ##           name: eth1
    ##       version: 2
    ##     userData:
    ##       password: p
    ##       user: u
    ##   name: cloudinitdisk
    ##   type: cloudInitNoCloud
    ##
    volumes: []

mcp:
  enable: false
  labels:
  - key: machineconfiguration.openshift.io/role
    value: worker-realtime
  machineConfigSelector:
    matchExpressions:
      matchExpressions:
      - key: machineconfiguration.openshift.io/role
        operator: In
        values:
        - worker
        - worker-realtime
  nodeSelector:
    matchLabels:
      key: node-role.kubernetes.io/worker-realtime
      value: ''

PerformanceProfile:
  enable: false
  cpu:
    isolated: 4-39,44-79
    reserved: 0-3,40-43
  globallyDisableIrqLoadBalancing: true
  hugepages:
    defaultHugepagesSize: 1G
    pages:
    - count: 8
      size: 1G
  nodeSelector:
    key: node-role.kubernetes.io/worker-realtime
    value: ''
  numa:
    topologyPolicy: single-numa-node
  realTimeKernel:
    enabled: true
  workloadHints:
    highPowerConsumption: true
    realTime: true

# NETWORK
nncp:
  enable: false
  nncps:
  - name: 1
    interfaces:
    - name: br1
      type: linux-bridge
      state: up
      ports:
      - eno3
    nodeSelector:
      key: node-role.kubernetes.io/worker
      value: ""

nad:
  enable: false
  name: bridge-nad
  network:
    bridge: br1
    cniVersion: 0.3.1
    ipam: '{}'
    macspoofchk: true
    name: bridge-network
    preserveDefaultVlan: false
    type: cnv-bridge
    vlan: 861

SriovNetwork:
  enable: false
  SriovNetworks:
  - name: 1
    namespace: openshift-sriov-network-operator
    resourceName: sriov_net

SriovNetworkNodePolicy:
  enable: false
  SriovNetworkNodePolicys:
  - name: 1
    namespace: openshift-sriov-network-operator
    nicSelector:
      pfNames:
      - eno2
      - eno2
      - eno2
    nodeSelector:
      key: feature.node.kubernetes.io/network-sriov.capable
      value: true
    numVfs: 32
    resourceName: sriov_net

# STORAGE
dv:
  enable: false
  pvc:
    accessModes:
    - ReadWriteOnce
    enable: false
    resources:
      requests:
        storage: 1Gi
    storageClassName: ocs-storagecluster-ceph-rbd
    volumeMode: Block
  source:
    blank:
      enable: false
    registry:
      pullMethod: node
      secretRef: pull-secret
      url: registry.redhat.io/rhel8/rhel-guest-image:latest

pvc:
  enable: false
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-ceph-rbd