{{- if .Values.vm.enable }}
{{- $initialContext := . }}
{{- range .Values.vm.vms }}
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  namespace: {{ $initialContext.Release.Namespace }}
  name: {{ $initialContext.Release.Name }}-{{ .name }}-vm
spec:
  running: {{ .running }}
  template:
    metadata:
      labels:
        kubevirt.io/vm: {{ $initialContext.Release.Name }}-{{ .name }}-vm
      {{- include "vm.spec.template.metadata.annotations" . | indent 6 }}
    spec:
      {{- include "vm.spec.template.spec.nodeSelector" . | indent 6 }}
      {{- include "vm.spec.template.spec.tolerations" . | indent 6 }}
      domain:
        {{- include "vm.spec.template.spec.domain.ioThreadsPolicy" . | indent 8 }}
        {{- include "vm.spec.template.spec.domain.cpu" . | indent 8 }}
        {{- include "vm.spec.template.spec.domain.memory" . | indent 8 }}
        devices:
            {{- include "vm.spec.template.spec.domain.devices" . | indent 10 }}
          rng: {}
        machine:
          type: ""
        {{- include "vm.spec.template.spec.domain.resources.requests.memory" . | indent 8 }}
      terminationGracePeriodSeconds: 0
      volumes:
      - containerDisk:
          image: {{ .image }}
        name: containerdisk
      {{- include "vm.spec.template.spec.volumes.cloudInitNoCloud" . | indent 6 }}
        name: cloudinitdisk
      networks:
        {{- include "vm.spec.template.spec.networks" . | indent 8 }}
---
{{- end }}
{{- end }}
    
