{{- if .Values.vm.enable }}
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-vm
spec:
  running: {{ .Values.vm.running }}

  {{- if .Values.vm.template }}
  template:

    {{- if .Values.vm.template.metadata }}
    metadata:
      {{- include "vm.spec.template.metadata.labels" . | indent 6 }}
      {{- include "vm.spec.template.metadata.annotations" . | indent 6 }}
    {{- end }}

    {{- if .Values.vm.template.spec }}
    spec:
      {{- include "vm.spec.template.spec.nodeSelector" . | indent 6 }}
      {{- include "vm.spec.template.spec.tolerations" . | indent 6 }}

      {{- if .Values.vm.template.spec.domain }}
      {{- $domain := .Values.vm.template.spec.domain }}
      domain:
        {{- include "vm.spec.template.spec.domain.ioThreadsPolicy" . | indent 6 }}
        {{- include "vm.spec.template.spec.domain.cpu" . | indent 8 }}
        {{- include "vm.spec.template.spec.domain.memory" . | indent 8 }}
        {{- include "vm.spec.template.spec.domain.devices" . | indent 8 }}
        {{- include "vm.spec.template.spec.domain.resources.requests.memory" . | indent 8 }}
      {{- end }}

      {{- include "vm.spec.template.spec.volumes" . | indent 6 }}
      {{- include "vm.spec.template.spec.terminationGracePeriodSeconds" . | indent 4 }}
      {{- include "vm.spec.template.spec.networks" . | indent 6 }}
    {{- end }}

  {{- end }}

  {{- include "vm.spec.dataVolumeTemplates" . }}
---
{{- end }}
    
