{{- if .Values.vm.enable }}
{{- $initialContext := . }}
{{- range .Values.vm.vms }}
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  namespace: {{ $initialContext.Release.Namespace }}
  name: {{ $initialContext.Release.Name }}-{{ .name }}-vm
spec:
  running: {{ .running }}
  template:
    metadata:
      {{- include "vm.spec.template.metadata" . }}
    spec:
      {{- include "vm.spec.template.spec" . }}
---
{{- end }}
{{- end }}
    
