{{- if .Values.dv.enable }}
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: {{ .Release.Name }}-dv
spec:
  {{- include "dv.spec.sourceRef" . | indent 2 }}
  {{- include "dv.spec.storage" . | indent 2 }}

  {{- if.Values.dv.source }}
  source:
    {{- include "dv.spec.source.registry" . | indent 4 }}
    {{- include "dv.spec.source.blank" . | indent 4 }}
    {{- include "dv.spec.source.pvc" . | indent 4 }}
  {{- end }}
  {{- if .Values.dv.pvc.enable }}
  pvc:
    {{- include "dv.spec.pvc" . | indent 4 }}
{{- end }}
{{- end }}