{{- if .Values.dv.enable }}
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: {{ .Release.Name }}-dv
spec:
  source:
    blank: {}
  {{- if .Values.dv.pvc.enable }}
  pvc:
    accessModes:
        {{- include "dv.spec.pvc.accessModes" . | indent 4 }}
    storageClassName: {{ .Values.dv.pvc.storageClassName }}
    volumeMode: {{ .Values.dv.pvc.volumeMode }}
    resources:
      requests:
          storage: {{ .Values.dv.pvc.resources.requests.storage }}
{{- end }}
{{- end }}