{{- if .Values.nad.enable }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Values.nad.name }} 
  namespace: {{ .Release.namespace }}
spec:
  config:
    {{- include "nad.spec.config" . }}
{{- end }}