{{- if .Values.vm.enable }}
{{- $initialContext := . }}
{{- range .Values.vm.vms }}
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  namespace: {{ $initialContext.Release.namespace }}
  name: {{ $initialContext.Release.Name }}-{{ .name }}-vm
spec:
  running: {{ .running }}
  template:
    metadata:
      labels:
        kubevirt.io/vm: {{ $initialContext.Release.Name }}-{{ .name }}-vm
    spec:
      {{- include "vm.spec.template.spec.nodeSelector" . | indent 6 }}
      domain:
        devices:
          interfaces:
            {{- include "vm.spec.template.spec.domain.devices" . | indent 12 }}
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          rng: {}
        machine:
          type: ""
        resources:
          requests:
            memory: 1024M
      terminationGracePeriodSeconds: 0
      volumes:
      - containerDisk:
          image: {{ .image }}
        name: containerdisk
      {{- include "vm.spec.template.spec.volumes.cloudInitNoCloud" . | indent 6 }}
        name: cloudinitdisk
      networks:
        {{- include "vm.spec.template.spec.networks" . | indent 8 }}
---
{{- end }}
{{- end }}
    
