{{- if .Values.vm.enable }}
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  namespace: {{ .Release.namespace }}
  name: {{ .Release.Name }}-vm
spec:
  running: {{ .Values.vm.running }}
  template:
    metadata:
      labels:
        kubevirt.io/vm: {{ .Release.Name }}-vm
    spec:
      {{- include "vm.spec.template.spec.nodeSelector" . | indent 6 }}
      domain:
        devices:
          interfaces:
            {{- include "vm.spec.template.spec.domain.devices" . | indent 12 }}
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          rng: {}
        machine:
          type: ""
        resources:
          requests:
            memory: 1024M
      terminationGracePeriodSeconds: 0
      volumes:
      - containerDisk:
          image: {{ .Values.vm.image }}
        name: containerdisk
      {{- include "vm.spec.template.spec.volumes.cloudInitNoCloud" . | indent 6 }}
          userData: |-
            #cloud-config
            password: password
            chpasswd: { expire: False }
        name: cloudinitdisk
      networks:
        {{- include "vm.spec.template.spec.networks" . | indent 8 }}
{{- end }}
    
